<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>AzureArchive.VideoTools.Formats</AssemblyName>
    <RootNamespace>AzureArchive.VideoTools.Formats</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzureArchive.VideoTools.Core\AzureArchive.VideoTools.Core.csproj" />
  </ItemGroup>
</Project>
