<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="Exists('..\..\Rukari.Lib\Rukari.Lib.csproj')">
    <ProjectReference Include="..\..\Rukari.Lib\Rukari.Lib.csproj" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('..\..\Rukari.Lib\Rukari.Lib.csproj')">
    <Reference Include="Rukari.Lib" HintPath="..\..\lib\Rukari.Lib.dll" Private="false" />
  </ItemGroup>
</Project>
