namespace Rukari.Lib.Tests;

internal static class Program
{
    private static int Main()
    {
        (string Name, Action Run)[] tests =
        {
            (nameof(ModSettingsTests.RegistrationWorksWithoutAProjectAndKeepsIndependentSnapshots), ModSettingsTests.RegistrationWorksWithoutAProjectAndKeepsIndependentSnapshots),
            (nameof(ModSettingsTests.DuplicateOwnersAndInvalidContentNeverReplaceExistingPages), ModSettingsTests.DuplicateOwnersAndInvalidContentNeverReplaceExistingPages),
            (nameof(ModSettingsTests.OldLeasesCannotRemoveReplacementSettingsPages), ModSettingsTests.OldLeasesCannotRemoveReplacementSettingsPages),
            (nameof(ModSettingsTests.PageLifecyclePairsOnceAcrossSelectionClosingAndDisposal), ModSettingsTests.PageLifecyclePairsOnceAcrossSelectionClosingAndDisposal),
            (nameof(ModSettingsTests.PageAndLoggerFailuresDoNotBreakOtherPagesOrPreventRetry), ModSettingsTests.PageAndLoggerFailuresDoNotBreakOtherPagesOrPreventRetry),
            (nameof(ModSettingsTests.DrawFailuresReleaseThePageAndDoNotRepeatEveryFrame), ModSettingsTests.DrawFailuresReleaseThePageAndDoNotRepeatEveryFrame),
            (nameof(ModSettingsTests.AnInvisibleOrFailingNativeHostNeverClaimsSuccessfulOpening), ModSettingsTests.AnInvisibleOrFailingNativeHostNeverClaimsSuccessfulOpening),
            (nameof(ModSettingsTests.WorkerOperationsCannotTouchWindowOrPageCallbacks), ModSettingsTests.WorkerOperationsCannotTouchWindowOrPageCallbacks),
            (nameof(ModSettingsTests.ReentrantPageCallbacksCannotCorruptSelectionOrRegistration), ModSettingsTests.ReentrantPageCallbacksCannotCorruptSelectionOrRegistration),
            (nameof(EmbeddedDirectiveTests.OfficialAndForeignLinesKeepTheirExactBytes), EmbeddedDirectiveTests.OfficialAndForeignLinesKeepTheirExactBytes),
            (nameof(EmbeddedDirectiveTests.RegisteredAavtFilteringLeavesFlLinesByteExact), EmbeddedDirectiveTests.RegisteredAavtFilteringLeavesFlLinesByteExact),
            (nameof(EmbeddedDirectiveTests.LongestTokenRouteOwnsEachLineInEitherRegistrationOrder), EmbeddedDirectiveTests.LongestTokenRouteOwnsEachLineInEitherRegistrationOrder),
            (nameof(EmbeddedDirectiveTests.AllModulesSeeTheFinalTextBeforeAnyCallbackExecutes), EmbeddedDirectiveTests.AllModulesSeeTheFinalTextBeforeAnyCallbackExecutes),
            (nameof(EmbeddedDirectiveTests.MalformedOwnedInstructionsStillReachTheirOwner), EmbeddedDirectiveTests.MalformedOwnedInstructionsStillReachTheirOwner),
            (nameof(EmbeddedDirectiveTests.MultiRouteRegistrationConflictsAreAtomic), EmbeddedDirectiveTests.MultiRouteRegistrationConflictsAreAtomic),
            (nameof(EmbeddedDirectiveTests.InvalidNamespacesAndExcessiveRegistrationsAreRejected), EmbeddedDirectiveTests.InvalidNamespacesAndExcessiveRegistrationsAreRejected),
            (nameof(EmbeddedDirectiveTests.RemovedLeasesCannotRemoveReplacementRegistrations), EmbeddedDirectiveTests.RemovedLeasesCannotRemoveReplacementRegistrations),
            (nameof(EmbeddedDirectiveTests.WorkerSanitizationHasNoCallbacksAndUsesImmutableSnapshots), EmbeddedDirectiveTests.WorkerSanitizationHasNoCallbacksAndUsesImmutableSnapshots),
            (nameof(EmbeddedDirectiveTests.CallbackFailuresAndLoggerFailuresDoNotAffectOtherMods), EmbeddedDirectiveTests.CallbackFailuresAndLoggerFailuresDoNotAffectOtherMods),
            (nameof(EmbeddedDirectiveTests.OwnerFilteredSnapshotsResolveForeignChildrenBeforeRetainingParents), EmbeddedDirectiveTests.OwnerFilteredSnapshotsResolveForeignChildrenBeforeRetainingParents),
            (nameof(EmbeddedDirectiveTests.OwnerFilteredSnapshotsKeepOwnershipStableAcrossRegistrationChanges), EmbeddedDirectiveTests.OwnerFilteredSnapshotsKeepOwnershipStableAcrossRegistrationChanges),
            (nameof(EmbeddedDirectiveTests.NestedDispatchRetainsItsOwnImmutableContext), EmbeddedDirectiveTests.NestedDispatchRetainsItsOwnImmutableContext),
            (nameof(EmbeddedDirectiveTests.CallbackRegistryChangesTakeEffectAtTheNextSnapshot), EmbeddedDirectiveTests.CallbackRegistryChangesTakeEffectAtTheNextSnapshot),
            (nameof(EmbeddedDirectiveTests.ReadinessAndShutdownNeverSilentlyConsumeUnownedText), EmbeddedDirectiveTests.ReadinessAndShutdownNeverSilentlyConsumeUnownedText),
            (nameof(EmbeddedDirectiveTests.EmptyAndSingleLineDocumentsRetainTheirBoundaries), EmbeddedDirectiveTests.EmptyAndSingleLineDocumentsRetainTheirBoundaries),
            (nameof(EmbeddedDirectiveTests.CompilationFamiliesKeepSeparateAuthorityAndSharedCorrelation), EmbeddedDirectiveTests.CompilationFamiliesKeepSeparateAuthorityAndSharedCorrelation),
            (nameof(EmbeddedDirectiveTests.CompilationTrackerCanUnwindAnExceptionAndStartFresh), EmbeddedDirectiveTests.CompilationTrackerCanUnwindAnExceptionAndStartFresh),
            (nameof(ToolPresentationTests.NodeToolsRequireAnOpenLoadedInspector), ToolPresentationTests.NodeToolsRequireAnOpenLoadedInspector),
            (nameof(ToolPresentationTests.OfficialWindowsHideToolsWithoutClosingTheWorkspace), ToolPresentationTests.OfficialWindowsHideToolsWithoutClosingTheWorkspace),
            (nameof(ToolPresentationTests.ButtonTextHasContrastInEveryVisualState), ToolPresentationTests.ButtonTextHasContrastInEveryVisualState),
            (nameof(ToolPresentationTests.EmptyVoicePanelDoesNotReserveEightEmptyRows), ToolPresentationTests.EmptyVoicePanelDoesNotReserveEightEmptyRows),
            (nameof(ToolPresentationTests.DrawerFitsScreensAndScalesWithLongContent), ToolPresentationTests.DrawerFitsScreensAndScalesWithLongContent),
            (nameof(ToolPresentationTests.ChinesePageTitlesFitAndLongLabelsStayOnOneLine), ToolPresentationTests.ChinesePageTitlesFitAndLongLabelsStayOnOneLine),
            (nameof(ToolPresentationTests.LeftSidebarLeavesTheOfficialRightWorkspaceClear), ToolPresentationTests.LeftSidebarLeavesTheOfficialRightWorkspaceClear),
            (nameof(ToolPresentationTests.RailButtonsStayFixedWhileModulesOpenCloseAndResize), ToolPresentationTests.RailButtonsStayFixedWhileModulesOpenCloseAndResize),
            (nameof(ToolPresentationTests.ToggleHandleNeverOverlapsAModuleButton), ToolPresentationTests.ToggleHandleNeverOverlapsAModuleButton),
            (nameof(ToolPresentationTests.RailIconAccentsAreDistinctPerModule), ToolPresentationTests.RailIconAccentsAreDistinctPerModule),
            (nameof(ToolPresentationTests.RailGlyphsResolveForKnownAndFutureModules), ToolPresentationTests.RailGlyphsResolveForKnownAndFutureModules),
            (nameof(ToolPresentationTests.RailPlacementUsesBottomUpScreenCoordinates), ToolPresentationTests.RailPlacementUsesBottomUpScreenCoordinates),
            (nameof(ToolPresentationTests.MasterModuleResolvesToItsOwnGlyph), ToolPresentationTests.MasterModuleResolvesToItsOwnGlyph),
            (nameof(ToolPresentationTests.PanelChromeStaysInsideTheFrame), ToolPresentationTests.PanelChromeStaysInsideTheFrame),
            (nameof(ToolPresentationTests.SharedButtonsFitTheOfficialPlate), ToolPresentationTests.SharedButtonsFitTheOfficialPlate),
            (nameof(ToolPresentationTests.ModuleColumnAdaptsToTheLongestName), ToolPresentationTests.ModuleColumnAdaptsToTheLongestName),
            (nameof(ToolPresentationTests.HostedPageGetsItsOwnSheetWidth), ToolPresentationTests.HostedPageGetsItsOwnSheetWidth),
            (nameof(ToolPresentationTests.HostedContentRectangleRoundTripsIntoTheEditorsOwnCoordinates), ToolPresentationTests.HostedContentRectangleRoundTripsIntoTheEditorsOwnCoordinates),
            (nameof(ToolPresentationTests.HostedControlsStayInsideTheirSheet), ToolPresentationTests.HostedControlsStayInsideTheirSheet),
            (nameof(ToolPresentationTests.TopDownBandsStackDownward), ToolPresentationTests.TopDownBandsStackDownward),
            (nameof(ToolModuleCardTests.TheCardScrollsInsteadOfShrinkingTheRail), ToolModuleCardTests.TheCardScrollsInsteadOfShrinkingTheRail),
            (nameof(ToolModuleCardTests.TheCardShowsEveryRowWhileTheyFit), ToolModuleCardTests.TheCardShowsEveryRowWhileTheyFit),
            (nameof(ToolModuleCardTests.TheSixthModuleStartsTheScrolling), ToolModuleCardTests.TheSixthModuleStartsTheScrolling),
            (nameof(ToolModuleCardTests.EveryModuleStaysReachableThroughTheScrollbar), ToolModuleCardTests.EveryModuleStaysReachableThroughTheScrollbar),
            (nameof(ToolModuleCardTests.ToolScrollKeepsTheWheelAndTheThumbInAgreement), ToolModuleCardTests.ToolScrollKeepsTheWheelAndTheThumbInAgreement),
            (nameof(ToolModuleCardTests.TheCardHeaderCarriesItsTitleAndCollapseControl), ToolModuleCardTests.TheCardHeaderCarriesItsTitleAndCollapseControl),
            (nameof(CaptionTests.LrcImportKeepsTheSongsOwnBeats), CaptionTests.LrcImportKeepsTheSongsOwnBeats),
            (nameof(CaptionTests.SrtAndAssImportKeepTheirOwnTiming), CaptionTests.SrtAndAssImportKeepTheirOwnTiming),
            (nameof(CaptionTests.TheTypewriterRevealsOneCharacterAtATime), CaptionTests.TheTypewriterRevealsOneCharacterAtATime),
            (nameof(CaptionTests.CaptionMotionNeverLeavesItsBounds), CaptionTests.CaptionMotionNeverLeavesItsBounds),
            (nameof(CaptionTests.CaptionMotionIsDeterministicAndSmooth), CaptionTests.CaptionMotionIsDeterministicAndSmooth),
            (nameof(CaptionTests.CaptionPlacementAvoidsWhatTheSceneNeeds), CaptionTests.CaptionPlacementAvoidsWhatTheSceneNeeds),
            (nameof(CaptionTests.ACinematicSceneGivesTheCaptionMoreRoom), CaptionTests.ACinematicSceneGivesTheCaptionMoreRoom),
            (nameof(CaptionTests.AUsableAreaKeepsCaptionsOffTheEditorsPreviewPane), CaptionTests.AUsableAreaKeepsCaptionsOffTheEditorsPreviewPane),
            (nameof(CaptionTests.TtfNamesAreReadFromAFontFileOrReportedAsBroken), CaptionTests.TtfNamesAreReadFromAFontFileOrReportedAsBroken),
            (nameof(CaptionTests.TheCaptionLineEditorKeepsItsCaretAndItsText), CaptionTests.TheCaptionLineEditorKeepsItsCaretAndItsText),
            (nameof(CaptionTests.TheSheetLayersStylesAndFindsItsOwnCaptions), CaptionTests.TheSheetLayersStylesAndFindsItsOwnCaptions),
            (nameof(AtlasSpriteCatalogTests.AtlasMetadataGivesEveryRecordedSpriteItsRectangleAndBorder), AtlasSpriteCatalogTests.AtlasMetadataGivesEveryRecordedSpriteItsRectangleAndBorder),
            (nameof(AtlasSpriteCatalogTests.AnUnusableAtlasMetadataDocumentIsRejectedInsteadOfThrowing), AtlasSpriteCatalogTests.AnUnusableAtlasMetadataDocumentIsRejectedInsteadOfThrowing),
            (nameof(AtlasSpriteCatalogTests.ExportPathsPairAnAtlasImageWithItsMetadata), AtlasSpriteCatalogTests.ExportPathsPairAnAtlasImageWithItsMetadata),
            (nameof(AtlasSpriteCatalogTests.TheDecodedExportOnDiskAgreesWithTheParser), AtlasSpriteCatalogTests.TheDecodedExportOnDiskAgreesWithTheParser),
            (nameof(BundledUiAssetsTests.SkinFollowsTheRuntimeAndKeepsOneVerifiedSnapshot), BundledUiAssetsTests.SkinFollowsTheRuntimeAndKeepsOneVerifiedSnapshot),
            (nameof(BundledUiAssetsTests.MissingOrMismatchedSkinFailsAsAWhole), BundledUiAssetsTests.MissingOrMismatchedSkinFailsAsAWhole),
            (nameof(BundledUiAssetsTests.SkinManifestRejectsDuplicatesAndForeignPaths), BundledUiAssetsTests.SkinManifestRejectsDuplicatesAndForeignPaths),
            (nameof(BundledUiAssetsTests.ShippedSkinContainsTheChromeAndValidSpriteBounds), BundledUiAssetsTests.ShippedSkinContainsTheChromeAndValidSpriteBounds),
            (nameof(ToolTreeStateTests.TheRailIconOpensTheColumnAndSelectsNothing), ToolTreeStateTests.TheRailIconOpensTheColumnAndSelectsNothing),
            (nameof(ToolTreeStateTests.OnePressIsOneVisibleLevel), ToolTreeStateTests.OnePressIsOneVisibleLevel),
            (nameof(ToolTreeStateTests.AnOpenColumnWithNoModuleLightsNoButton), ToolTreeStateTests.AnOpenColumnWithNoModuleLightsNoButton),
            (nameof(ToolTreeStateTests.OnlyOneModuleIsOpenAtATime), ToolTreeStateTests.OnlyOneModuleIsOpenAtATime),
            (nameof(ToolTreeStateTests.OnlyOneEntryIsOpenAtATime), ToolTreeStateTests.OnlyOneEntryIsOpenAtATime),
            (nameof(ToolTreeStateTests.CollapseWalksBackOneLevelAtATime), ToolTreeStateTests.CollapseWalksBackOneLevelAtATime),
            (nameof(ToolTreeStateTests.UnregisteredModulesCannotStayOpen), ToolTreeStateTests.UnregisteredModulesCannotStayOpen),
            (nameof(ToolTreeStateTests.AnUnloadedEntryClosesThePanelAndKeepsTheColumn), ToolTreeStateTests.AnUnloadedEntryClosesThePanelAndKeepsTheColumn),
            (nameof(ToolTreeStateTests.TreeDepthDecidesHowManyColumnsExist), ToolTreeStateTests.TreeDepthDecidesHowManyColumnsExist),
            (nameof(ToolTreeStateTests.GuardBandCoversTheEntryColumnButNeverThePanel), ToolTreeStateTests.GuardBandCoversTheEntryColumnButNeverThePanel),
            (nameof(ToolTreeStateTests.TreeColumnsPopOutToTheRightWithoutOverlapping), ToolTreeStateTests.TreeColumnsPopOutToTheRightWithoutOverlapping),
            (nameof(ToolTreeStateTests.ShippedTwoModuleTreeStaysInTheLeftBand), ToolTreeStateTests.ShippedTwoModuleTreeStaysInTheLeftBand),
            (nameof(ToolListNavigationTests.ClosingReopeningAndSwitchingPagesRetainOnlyTheirOwnNavigation), ToolListNavigationTests.ClosingReopeningAndSwitchingPagesRetainOnlyTheirOwnNavigation),
            (nameof(ToolListNavigationTests.DifferentProjectsAndSourcesNeverShareQueriesOrPages), ToolListNavigationTests.DifferentProjectsAndSourcesNeverShareQueriesOrPages),
            (nameof(ToolListNavigationTests.LocatePrefersExactNamesAndOtherwiseTheFirstContainingName), ToolListNavigationTests.LocatePrefersExactNamesAndOtherwiseTheFirstContainingName),
            (nameof(ToolListNavigationTests.RedrawAndRepeatedQueriesNeverUndoManualPaging), ToolListNavigationTests.RedrawAndRepeatedQueriesNeverUndoManualPaging),
            (nameof(ToolListNavigationTests.ClearingLocateSearchPreservesTheBrowsedPage), ToolListNavigationTests.ClearingLocateSearchPreservesTheBrowsedPage),
            (nameof(ToolListNavigationTests.ExplicitLocateReturnsToCurrentMatchAndLeavesFilterPagingAlone), ToolListNavigationTests.ExplicitLocateReturnsToCurrentMatchAndLeavesFilterPagingAlone),
            (nameof(ToolListNavigationTests.UnmatchedQueriesAndEmptyListsDoNotJumpOrThrow), ToolListNavigationTests.UnmatchedQueriesAndEmptyListsDoNotJumpOrThrow),
            (nameof(ToolListNavigationTests.ChangedCatalogsAndPageSizesClampWithoutRelocatingStaleMatches), ToolListNavigationTests.ChangedCatalogsAndPageSizesClampWithoutRelocatingStaleMatches),
            (nameof(ToolListNavigationTests.UnchangedSnapshotsReuseTheirViewAndNewSnapshotsRefreshHitsWithoutJumping), ToolListNavigationTests.UnchangedSnapshotsReuseTheirViewAndNewSnapshotsRefreshHitsWithoutJumping),
            (nameof(ToolListNavigationTests.FilterKeepsLegacySubsetPagingAndQueryResetBehaviour), ToolListNavigationTests.FilterKeepsLegacySubsetPagingAndQueryResetBehaviour),
            (nameof(ToolListNavigationTests.NavigationNeverMutatesResourceLabelsOrCallsAnApplyAction), ToolListNavigationTests.NavigationNeverMutatesResourceLabelsOrCallsAnApplyAction),
            (nameof(ToolPanelBuilderTests.RowsAreReservedInOrderAndCellsSplitThemEvenly), ToolPanelBuilderTests.RowsAreReservedInOrderAndCellsSplitThemEvenly),
            (nameof(ToolPanelBuilderTests.HostedControlIdsMustBeUniqueWithinAFrame), ToolPanelBuilderTests.HostedControlIdsMustBeUniqueWithinAFrame),
            (nameof(ToolPanelBuilderTests.OnlyTheControlUnderThePressCanBeClicked), ToolPanelBuilderTests.OnlyTheControlUnderThePressCanBeClicked),
            (nameof(ToolPanelBuilderTests.StyledButtonsKeepTheLegacyButtonAndRespectInputState), ToolPanelBuilderTests.StyledButtonsKeepTheLegacyButtonAndRespectInputState),
            (nameof(ToolPanelBuilderTests.APressOutsideEveryControlBelongsToNobody), ToolPanelBuilderTests.APressOutsideEveryControlBelongsToNobody),
            (nameof(ToolPanelBuilderTests.DragOnlyContinuesWhileThePressStaysOnTheArea), ToolPanelBuilderTests.DragOnlyContinuesWhileThePressStaysOnTheArea),
            (nameof(ToolPanelBuilderTests.EverySurfaceStyleResolvesToADrawableSurface), ToolPanelBuilderTests.EverySurfaceStyleResolvesToADrawableSurface),
            (nameof(ToolPanelBuilderTests.HostedSheetAndTextMeasurementAreBounded), ToolPanelBuilderTests.HostedSheetAndTextMeasurementAreBounded),
            (nameof(ToolPanelBuilderTests.HostedPageSeesItsPixelRectangle), ToolPanelBuilderTests.HostedPageSeesItsPixelRectangle),
            (nameof(ToolPanelSessionTests.ShowAndHideCallbacksFireOncePerTransition), ToolPanelSessionTests.ShowAndHideCallbacksFireOncePerTransition),
            (nameof(RuntimeHostTests.ReadinessPreventsPrematureAndPostStopWrites), RuntimeHostTests.ReadinessPreventsPrematureAndPostStopWrites),
            (nameof(RuntimeHostTests.StartAndPumpRequireCreatingThread), RuntimeHostTests.StartAndPumpRequireCreatingThread),
            (nameof(RuntimeHostTests.MainThreadCallsCompleteImmediately), RuntimeHostTests.MainThreadCallsCompleteImmediately),
            (nameof(RuntimeHostTests.WorkersQueueInOrderUntilMainThreadPumps), RuntimeHostTests.WorkersQueueInOrderUntilMainThreadPumps),
            (nameof(RuntimeHostTests.FullQueueRejectsOnlyTheNewOperation), RuntimeHostTests.FullQueueRejectsOnlyTheNewOperation),
            (nameof(RuntimeHostTests.PreCancelledOperationNeverWrites), RuntimeHostTests.PreCancelledOperationNeverWrites),
            (nameof(RuntimeHostTests.QueuedCancellationCompletesWithoutPumpAndReleasesCapacity), RuntimeHostTests.QueuedCancellationCompletesWithoutPumpAndReleasesCapacity),
            (nameof(RuntimeHostTests.CancellationDuringWritePreservesActualResult), RuntimeHostTests.CancellationDuringWritePreservesActualResult),
            (nameof(RuntimeHostTests.StopCancelsPendingWritesFromAnyThread), RuntimeHostTests.StopCancelsPendingWritesFromAnyThread),
            (nameof(RuntimeHostTests.StopDuringWritePreservesActualResult), RuntimeHostTests.StopDuringWritePreservesActualResult),
            (nameof(RuntimeHostTests.FailedOperationDoesNotPoisonFollowingWrites), RuntimeHostTests.FailedOperationDoesNotPoisonFollowingWrites),
            (nameof(RuntimeHostTests.NullProviderResultDoesNotStrandFollowingWrites), RuntimeHostTests.NullProviderResultDoesNotStrandFollowingWrites),
            (nameof(RuntimeHostTests.ExplicitProviderFailureIsPreserved), RuntimeHostTests.ExplicitProviderFailureIsPreserved),
            (nameof(RuntimeHostTests.ProviderCancellationExceptionDoesNotClaimRollback), RuntimeHostTests.ProviderCancellationExceptionDoesNotClaimRollback),
            (nameof(RuntimeHostTests.ProviderCanDispatchNestedMainThreadWork), RuntimeHostTests.ProviderCanDispatchNestedMainThreadWork),
            (nameof(RuntimeHostTests.DuplicateServiceAndCapabilityNeverReplaceExistingOwner), RuntimeHostTests.DuplicateServiceAndCapabilityNeverReplaceExistingOwner),
            (nameof(RuntimeHostTests.OldRegistrationLeaseCannotRemoveReplacement), RuntimeHostTests.OldRegistrationLeaseCannotRemoveReplacement),
            (nameof(RuntimeHostTests.ForeignOwnerCannotPublishCapability), RuntimeHostTests.ForeignOwnerCannotPublishCapability),
            (nameof(RuntimeHostTests.BackgroundRegistrationCannotModifyRegistry), RuntimeHostTests.BackgroundRegistrationCannotModifyRegistry),
            (nameof(RuntimeHostTests.WorkersCanReadManagedServiceSnapshots), RuntimeHostTests.WorkersCanReadManagedServiceSnapshots),
            (nameof(RuntimeHostTests.StopRemovesServicesAndCapabilities), RuntimeHostTests.StopRemovesServicesAndCapabilities),
            (nameof(RuntimeHostTests.RegistryRemovalDoesNotDisposeProviderOnWrongThread), RuntimeHostTests.RegistryRemovalDoesNotDisposeProviderOnWrongThread),
            (nameof(RuntimeHostTests.GlobalRuntimeAttachmentCannotBeOverwrittenOrDetachedByAnotherHost), RuntimeHostTests.GlobalRuntimeAttachmentCannotBeOverwrittenOrDetachedByAnotherHost),
            (nameof(PublicContractTests.ApiAssemblyHasNoNativeOrFeatureDependencies), PublicContractTests.ApiAssemblyHasNoNativeOrFeatureDependencies),
            (nameof(PublicContractTests.ToolboxRegistrationKeepsItsOriginalArity), PublicContractTests.ToolboxRegistrationKeepsItsOriginalArity),
            (nameof(PublicContractTests.HostedButtonStyleKeepsTheFrozenSurfaceSignature), PublicContractTests.HostedButtonStyleKeepsTheFrozenSurfaceSignature),
            (nameof(PublicContractTests.ExportedContractsDoNotExposeNativeOrFeatureTypes), PublicContractTests.ExportedContractsDoNotExposeNativeOrFeatureTypes),
            (nameof(EditorDocumentSessionTests.RepeatedReadPreservesDraftUntilSelectionChanges), EditorDocumentSessionTests.RepeatedReadPreservesDraftUntilSelectionChanges),
            (nameof(EditorDocumentSessionTests.StaleRevisionAndForeignTokenCannotOverwriteTheLine), EditorDocumentSessionTests.StaleRevisionAndForeignTokenCannotOverwriteTheLine),
            (nameof(EditorDocumentSessionTests.IdenticalTextOnDifferentLinesDoesNotShareSelectionIdentity), EditorDocumentSessionTests.IdenticalTextOnDifferentLinesDoesNotShareSelectionIdentity),
            (nameof(EditorDocumentSessionTests.ReturningToSameLineCannotReviveAnOldDraft), EditorDocumentSessionTests.ReturningToSameLineCannotReviveAnOldDraft),
            (nameof(EditorDocumentSessionTests.OptionalInvalidationCapabilityRejectsAnOldDraftWithoutReadingLineB), EditorDocumentSessionTests.OptionalInvalidationCapabilityRejectsAnOldDraftWithoutReadingLineB),
            (nameof(EditorDocumentSessionTests.OptionalInvalidationGuardsPreserveTheTokenAndNeverTouchTheBackend), EditorDocumentSessionTests.OptionalInvalidationGuardsPreserveTheTokenAndNeverTouchTheBackend),
            (nameof(EditorDocumentSessionTests.ExplicitSelectionInvalidationWorksWithoutPollingIntermediateLine), EditorDocumentSessionTests.ExplicitSelectionInvalidationWorksWithoutPollingIntermediateLine),
            (nameof(EditorDocumentSessionTests.ExternalEditPreventsSharedUndoFromOverwritingIt), EditorDocumentSessionTests.ExternalEditPreventsSharedUndoFromOverwritingIt),
            (nameof(EditorDocumentSessionTests.TwoFeaturesShareOnlyTheLatestUndoTransaction), EditorDocumentSessionTests.TwoFeaturesShareOnlyTheLatestUndoTransaction),
            (nameof(EditorDocumentSessionTests.UnchangedWriteDoesNotConsumeOrReplaceTheExistingUndo), EditorDocumentSessionTests.UnchangedWriteDoesNotConsumeOrReplaceTheExistingUndo),
            (nameof(EditorDocumentSessionTests.FailedWriteDoesNotArmUndoAndRequiresAFreshDraft), EditorDocumentSessionTests.FailedWriteDoesNotArmUndoAndRequiresAFreshDraft),
            (nameof(EditorDocumentSessionTests.IncorrectWriteReadbackIsRejectedWithoutArmingUndo), EditorDocumentSessionTests.IncorrectWriteReadbackIsRejectedWithoutArmingUndo),
            (nameof(EditorDocumentSessionTests.ProviderExceptionsAndUnreadableSelectionInvalidateTheDraft), EditorDocumentSessionTests.ProviderExceptionsAndUnreadableSelectionInvalidateTheDraft),
            (nameof(EditorDocumentSessionTests.NotReadyAndWrongThreadNeverTouchTheBackend), EditorDocumentSessionTests.NotReadyAndWrongThreadNeverTouchTheBackend),
            (nameof(EditorDocumentSessionTests.ReentrantReadReplaceAndUndoAreBusyUntilWriteCompletes), EditorDocumentSessionTests.ReentrantReadReplaceAndUndoAreBusyUntilWriteCompletes),
            (nameof(CommandHelpTests.OnlyOneRowPerSyntaxReachesThePanel), CommandHelpTests.OnlyOneRowPerSyntaxReachesThePanel),
            (nameof(CommandHelpTests.WhitespaceAndControlCharactersAreFoldedAway), CommandHelpTests.WhitespaceAndControlCharactersAreFoldedAway),
            (nameof(CommandHelpTests.EmptyOrOversizedRowsAreRejected), CommandHelpTests.EmptyOrOversizedRowsAreRejected),
            (nameof(ToolHostedPageGuardTests.HeightGetterFailureIsIsolatedAndNeverRetriedEveryFrame), ToolHostedPageGuardTests.HeightGetterFailureIsIsolatedAndNeverRetriedEveryFrame),
            (nameof(ToolHostedPageGuardTests.WidthGetterFailureUsesFiniteFallbackAndSkipsTheProvider), ToolHostedPageGuardTests.WidthGetterFailureUsesFiniteFallbackAndSkipsTheProvider),
            (nameof(ToolHostedPageGuardTests.AVisiblePagesSizeFailureHidesItExactlyOnce), ToolHostedPageGuardTests.AVisiblePagesSizeFailureHidesItExactlyOnce),
            (nameof(ToolHostedPageGuardTests.PartialShownFailureGetsOneHiddenCallbackAndNoDraw), ToolHostedPageGuardTests.PartialShownFailureGetsOneHiddenCallbackAndNoDraw),
            (nameof(ToolHostedPageGuardTests.DrawFailureDiscardsPartialControlsDragFocusAndTyping), ToolHostedPageGuardTests.DrawFailureDiscardsPartialControlsDragFocusAndTyping),
            (nameof(ToolHostedPageGuardTests.HiddenCallbackFailureCannotPreventAnotherPageFromShowing), ToolHostedPageGuardTests.HiddenCallbackFailureCannotPreventAnotherPageFromShowing),
            (nameof(ToolHostedPageGuardTests.ExplicitCloseAndReturnPermitOneRetryOfTheSameRegistration), ToolHostedPageGuardTests.ExplicitCloseAndReturnPermitOneRetryOfTheSameRegistration),
            (nameof(ToolHostedPageGuardTests.SharedContentAndReusedPageIdsStillUseRegistrationIdentity), ToolHostedPageGuardTests.SharedContentAndReusedPageIdsStillUseRegistrationIdentity),
            (nameof(ToolHostedPageGuardTests.ValidDynamicSizesAndLegacyTwoMemberPagesRemainSupported), ToolHostedPageGuardTests.ValidDynamicSizesAndLegacyTwoMemberPagesRemainSupported),
            (nameof(ToolHostedPageGuardTests.FailureDiagnosticsAreBoundedAndCannotBreakTheGuard), ToolHostedPageGuardTests.FailureDiagnosticsAreBoundedAndCannotBreakTheGuard),
            (nameof(ToolHostedPageGuardTests.CallbackNavigationDiscardsTheOldFrameWithoutQuarantiningTheNewPage), ToolHostedPageGuardTests.CallbackNavigationDiscardsTheOldFrameWithoutQuarantiningTheNewPage),
            (nameof(ToolHostedPageGuardTests.FailedShownNavigationStillPairsTheDepartingLifecycle), ToolHostedPageGuardTests.FailedShownNavigationStillPairsTheDepartingLifecycle),
            (nameof(ToolHostedPageGuardTests.SizeGetterNavigationStopsFurtherCallbacksAndKeepsNewPageUsable), ToolHostedPageGuardTests.SizeGetterNavigationStopsFurtherCallbacksAndKeepsNewPageUsable),
            (nameof(ToolHostedPageGuardTests.CloseAndReopenInsideDrawCannotReuseTheOldFrameOrFailure), ToolHostedPageGuardTests.CloseAndReopenInsideDrawCannotReuseTheOldFrameOrFailure),
            (nameof(ToolHostedPageGuardTests.HiddenNavigationKeepsTheLatestSelectionAndItsOwnDiagnostics), ToolHostedPageGuardTests.HiddenNavigationKeepsTheLatestSelectionAndItsOwnDiagnostics),
        };

        var failed = 0;
        foreach (var (name, run) in tests)
        {
            try
            {
                run();
                Console.WriteLine($"PASS {name}");
            }
            catch (Exception exception)
            {
                failed++;
                Console.Error.WriteLine($"FAIL {name}: {exception}");
            }
        }

        Console.WriteLine($"{tests.Length - failed}/{tests.Length} Rukari lib tests passed.");
        return failed == 0 ? 0 : 1;
    }
}
